### ISSUE TITLE
JiJ'd Dependencies of Dependencies in dev env don't load

### ISSUE THREAD

**Issue by sylv256** [QuiltMC/quilt-loader#107]
![image](https://user-images.githubusercontent.com/18603248/185984161-916a9ac6-1e46-4bff-a724-6e498af095dd.png)
just try importing anything that uses jij'd dependencies and run in dev env and something like this will happen
I'm not sure if this is related to quilt loom or not, but it shouldn't be since they're jij'd and quilt loader is supposed to handle loading those
this happens with any mod loaded with `modImplementation`, `modRuntimeOnly`, etc. None of the JIJ'd jars inside these mod dependencies ever load in dev env, but they load perfectly fine in prod.

**Comment by TheGlitch76** [comment]
Works as intended; JiJ aren't loaded when depended on like that. You need to fix your POM so that Gradle pulls in the dependencies for you.

**Comment by sylv256** [comment]
this issue didn't happen in fabric, though. how is this intended?

**Comment by falkreon** [comment]
https://github.com/QuiltMC/quilt-kotlin-libraries/blob/main/fatjar/build.gradle.kts#L5-L13

The problem may be here, where the JIJ'd dependency did not declare *its* dependencies under a mod configuration. Is this the case?

**Comment by sylv256** [comment]
@TheGlitch76 me having to include every single JiJ'd dependency because loader isn't seeing the jars is not "working as intended"
re-open this issue.
![image](https://user-images.githubusercontent.com/18603248/185991964-c6a4c041-c92c-4946-8ece-c220f9e0a4e0.png)

**Comment by TheGlitch76** [comment]
https://github.com/FabricMC/fabric-loom/blob/3dc18a32d44ee44e6d393cabd893668422d7bf85/src/main/java/net/fabricmc/loom/configuration/mods/ModProcessor.java#L82

**Comment by sylv256** [comment]
is there any way to disable this behavior?
https://github.com/FabricMC/fabric-loom/commit/0206a4c59bf683effd39389eaf8fc4a9ed78b751 apparently this has been a thing, but this didn't happen in fabric before?

**Comment by sylv256** [comment]
This may be an issue with Modrinth's maven. I'll go ask them. Thank you.

**Comment by TheGlitch76** [comment]
> Apparently this has been a thing, but this wasn't a thing in fabric before?

Loom has worked this way for about as long as JiJ has been fully functional; JiJ was in the process of being integrated into the Fabric toolchain when that commit was added.

 I'm not 100% confident why your issue is occurring, because I haven't seen the entire buildscript, but I have a couple things to note:
 - If you depend on a mod through Modrinth, it's expected behavior that dependencies won't be pulled, and you'll have to add them manually. I'm confident it works this way on Fabric too; you can test it yourself
 - It's possible that certain other mods, like QLK, have a broken POM that causes it to not properly pull in the dependencies you need. This would happen regardless of if you used a mod with a broken POM on Quilt or Fabric.
