### ISSUE TITLE
Quilt Loader beta (0.18.1-beta.3) breaks FerriteCore

### ISSUE THREAD

**Issue by Oliver-makes-code** [QuiltMC/quilt-loader#136]
https://mclo.gs/7Jh9b8i

**Comment by AlexIIL** [comment]
This *might* be because FerriteCore blindly uses `InputStream.available()` to allocate a byte array to read from - which you're not meant to do. However we can fix it from quilt's side (assuming that's the issue anyway)

https://github.com/malte0811/FerriteCore/blob/a01508d14fe25e7f2071c468cb5abb52f4dc0f1a/Common/src/main/java/malte0811/ferritecore/classloading/FastImmutableMapDefiner.java#L68

**Comment by AlexIIL** [comment]
Can you retry with `0.18.1-beta.4`?

**Comment by Oliver-makes-code** [comment]
Still doesn't work, getting the same error

**Comment by AlexIIL** [comment]
Ah, that's unfortunate. I think this means I'll have to debug this properly.

**Comment by AlexIIL** [comment]
After some debugging I can confirm this is due to FerriteCore wrongly assuming `InputStream.available()` is usable in this way, since quilt-loader passes a `GZIPInputStream` for the input stream, which returns `1` from `available` when it's not empty.

**Comment by AlexIIL** [comment]
*Technically* we kinda need to fix this anyway since ferritecore is unlikely to release bugfixes for all of it's older versions...

**Comment by AlexIIL** [comment]
Okay, `0.18.1-beta.4` is now building which should fix this.

**Comment by AlexIIL** [comment]
I've tested `0.18.1-beta.4` locally and it seems to have fixed it - can you double-check?

**Comment by Oliver-makes-code** [comment]
Testing now

**Comment by Oliver-makes-code** [comment]
It works!
