### ISSUE TITLE
Suggestion: Make all private and protected Minecraft fields and methods automatically public by default

### ISSUE THREAD

**Issue by MalekiRe** [QuiltMC/quilt-loader#14]
I was having a conversation with a couple of individuals about fabric, and I had the idea of just by default why not have all Minecraft's fields and methods public, so you can always call the methods, or change the fields. The reasoning behind not doing this is because it could lead to an individual messing with something without understanding it, however, just by using mixins/accessors anyone can do that anyway, by setting all Fields and Methods to public it would ease and speed up mod development. I think we should trust the mod makers to know what they're doing, and having an artificial barrier of requiring someone to learn how to use accessors, as an example, or mixins, in order to use private fields or methods does no one any good.
![image](https://user-images.githubusercontent.com/50841145/117187848-38382980-ad91-11eb-8b8c-daecc0457e39.png)

**Comment by OroArmor** [comment]
No. private exists for a reason. If you *need* them, accessors are fine, but otherwise you are just breaking things to break them.

**Comment by yitzy299** [comment]
No. This is an awful idea

**Comment by Geolykt** [comment]
I have to also tell that it is not a good idea since private/protected and package protected visibillity modifiers all exist for a purpuse.
If that is not performed developers are going to use things that shouldn't be used directly. (for example in the arbitary case where a point is added to a hitbox. Developers may add the points directly to the underlying list of points, without updating the hitbox bounds, which the actual (public) API method would do.)

**Comment by MalekiRe** [comment]
Looks like no one wants it, closing the issue.
