### ISSUE TITLE
QuiltMemoryFileSystemProvider.newInputStream is "causing problems" by being slow

### ISSUE THREAD

**Issue by AlexIIL** [QuiltMC/quilt-loader#143]
Profiling started since this might be making startup time take 3 mins according to #142.

**Comment by SplendidAlakey** [comment]
Bear in mind, it's that slow specifically with a big modpack. Just on its own or only a few mods, it's fine.

**Comment by AlexIIL** [comment]
After some brief investigation it turns out this might be because it's getting called no less than `1232896` times in a small modpack *(just `quilted-fabric-api-4.0.0-beta.19+0.64.0-1.19.2.jar` and `requiem-2.0.0-beta.15.jar` - or 102 jar files)*. Of which only `7500` succeeded in finding the relevant file, so it might not be an issue with the function itself.

**Comment by AlexIIL** [comment]
I've optimized this quite a bit in https://github.com/QuiltMC/quilt-loader/commit/d3130dae3598727689eca4000ebff39ee68d1a4d (`0.18.1-beta.10`) and I think that should help a lot?

**Comment by AlexIIL** [comment]
...at least it would help if I actually pushed a buildable commit :p

**Comment by SplendidAlakey** [comment]
Sorry, took me a while to reply, because Prism took a while to catch up and add beta 10.

The patch helped a ton. My current numbers are:

- roughly 45sec before the debug success screen (down from 1min)
- roughly 40sec after that before the MC window appears (down from 5min)
- game loading itself is still as fast as 0.17.6
