### ISSUE TITLE
Passing a custom mod directory causes crashing.

### ISSUE THREAD

**Issue by piuvas** [QuiltMC/quilt-loader#148]
Crashing occurs whenever a custom mod directory is passed to Quilt.
There's a pattern with entrypoints, but I'm not sure.

| [Smooth Boot](https://mclo.gs/yV4uYaA) |
|-|
| Quilt Crash |

| [Ferritecore](https://mclo.gs/iM8X5tx) |
|-|
| Client Crash|

| [Sodium](https://mclo.gs/1Wonhw9) |
|-|
| Client Crash |

---
Reproducing:
- set the following flags: `-Dloader.modsDir=.velvet/mods/1.19.2 -Dloader.configDir=.velvet/config/1.19.2`
- get a mod that uses entrypoints (e.g. sodium or ferritecore)
- try launching the game
---
Related to: #20

**Comment by AlexIIL** [comment]
I'm having trouble reproducing this - plus, all of the crashes point to this being a problem with mappings rather than anything else. One thing I am interested in is how you've installed quilt-loader: some of the crashes point to you using `velvet-quilt-loader` rather than standard quilt loader, so can you try reinstalling quilt-loader `0.18.1-beta.12` from scratch and trying again?

(Beta 12 also improves the error message from the first crash, now it will print all of the known namespaces rather than just the one that isn't found).

**Comment by OroArmor** [comment]
It looks like your minecraft was not remapped when installing. Thats all i can tell.
Ferrite Core:
> at efu.<init>(SourceFile:459)
	at net.minecraft.client.main.Main.a(SourceFile:205)
	at net.minecraft.client.main.Main.main(SourceFile:51)

and Sodium:
> at efu.<init>(SourceFile:459)
	at net.minecraft.client.main.Main.a(SourceFile:205)
	at net.minecraft.client.main.Main.main(SourceFile:51)

Yes i know these look the same but i copied them each from the different logs. The reason i dont have anything from the smooth boot log is because it is the game log and doesnt seem to have any minecraft classes in the stacktrace besides main

**Comment by piuvas** [comment]
> I'm having trouble reproducing this - plus, all of the crashes point to this being a problem with mappings rather than anything else. One thing I am interested in is how you've installed quilt-loader: some of the crashes point to you using `velvet-quilt-loader` rather than standard quilt loader, so can you try reinstalling quilt-loader `0.18.1-beta.12` from scratch and trying again?

I was experimenting with my own quilt installer and I renamed the versions so that it wouldn't interfere with a regular installation for the sake of debugging (my project is called Velvet 😅). I'm ashamed to say that this is not reproducible with a regular quilt installation.
