### ISSUE TITLE
Significant loading slowdown between beta 28 and 29

### ISSUE THREAD

**Issue by SplendidAlakey** [QuiltMC/quilt-loader#197]
**MC** 1.19.2
**Quilt Loader** 0.18.1-beta.29

With the same exact modpack, it takes me:
- just under 2min before the game window appears and 3min45sec to load into the game on 0.17.8
- around 2.5min before the game window appears and around 4min to load into the game on 0.18.1-beta.28
- 5min before the game window appears and around 4min to load into the game on 0.18.1-beta.29

I'm ok with a slight slowdown seen in 0.18.x overall, but beta 29 is way too slow. Specifically the time it takes to load before the game window opens.

Not sure if any logs would be useful, so I'm just attaching the 3 instances between different versions for now:

0.17.8: https://gist.github.com/SplendidAlakey/49e98bbb3a24394ad8346a5132cc21c3#file-stable_latest-log
0.18.1-beta.28: https://gist.github.com/SplendidAlakey/49e98bbb3a24394ad8346a5132cc21c3#file-beta28_latest-log
0.18.1-beta.29: https://gist.github.com/SplendidAlakey/49e98bbb3a24394ad8346a5132cc21c3#file-beta29_latest-log

**Comment by AlexIIL** [comment]
Thanks for reporting these, however it would be really useful if you could run (and upload) sampling data for the beta.29 launch (not beta 30 - that removed some new functionality that might be responsible for the slowdown), rather than log files (since nothing is going wrong other than how long it takes, logs aren't quite as useful).

I'll write this up in a wiki, but you can do this by:
1. Downloading [JVisualVM](https://visualvm.github.io/)
2. Extracting the JVisualVM to a directory
3. Adding JVisualVM as an external tool in PrismLauncher/MultiMC (I'm assuming it's the same steps):
     1. Go to Settings > External Tools > JVisualVM and select the text box beneath.
     2. Locate the directory you extracted JVisualVM to, and then go into bin, and then select the executable. (So the final path will be something like `C:\Users\A\Documents\MyApps\JVisualVM\2.1.5\bin\visualvm.exe`
     3. Click the `check` button to make sure it worked.
4. Launch minecraft from the "list of instances" panel, and NOT the "per instances" panel by right-clicking on the instance and then hovering over `Launch`, then `JVisalVM`
5. Click on the "Sampler" tab (next to Overview, Monitor, Threads)
6. Tick the "Settings" box
7. Select "20" as the sampling frequency rather than "100" ms.
8. Click `CPU` to start profiling
9. Click `Launch` on the MultiMC "Waiting" window
10. Wait for minecraft to get to the loading screen, then click the `Stop` button in JVisualVM
11. Click the `Snapshot` button in JVisualVM.
12. Click the `Save` button (second button from the left, just above the list of threads)
13. Then select `Export Snapshot Data`, and save that somewhere.
14. Add that file to a zip (github doesn't allow you to upload .nps files directly).

**Comment by SplendidAlakey** [comment]
Thanks for the detailed instructions. Though, I had to also edit `visualvm/etc/visualvm.conf` file to point to the correct JDK before doing step 4, because by default it only looks for Oracle. And it took me embarrassingly long to find the Snapshot button, as it was completely hidden due to a small window size 🤦‍♂️

Anyways, here's the file: [snapshot_beta29.zip](https://github.com/QuiltMC/quilt-loader/files/10410227/snapshot_beta29.zip)

Also tested beta.30, the loading times did not improve, so you can probably discard those changes as a potential cause.

**Comment by AlexIIL** [comment]
Thanks! This was very helpful at pointing out that locating a class file is the biggest timesink at the moment - this could be caused by locating where a class is 3 times (when we should only do that once) or it could be because there are too many uncacheable classpath locations to load from. It also turns out that the transform cache prevented some classpath optimizations from working, so I've fixed that too - can you retry with beta 34?

**Comment by SplendidAlakey** [comment]
Beta 34 now takes 2.5min before the loading window opens, so the fix worked. 

However, I can't fully test it, as the update broke some of the mods I use. First one is [Kambrik](https://www.curseforge.com/minecraft/mc-mods/kambrik), second is [FireplaceLib](https://www.curseforge.com/minecraft/mc-mods/fireplace-lib), third is [Pehkui](https://www.curseforge.com/minecraft/mc-mods/pehkui) and the last* one is [Frame API](https://www.curseforge.com/minecraft/mc-mods/frame-api). Should I open separate issues for these?

*There are more mods, that crash with the same exact error as Pehkui and Frame API, so I'm going to stop binary searching here and hope that the same fix will resolve all of these.

Logs for FireplaceLib: https://gist.github.com/SplendidAlakey/49e98bbb3a24394ad8346a5132cc21c3#file-fireplace_crash-log
https://gist.github.com/SplendidAlakey/49e98bbb3a24394ad8346a5132cc21c3#file-fireplace_latest-log

Logs for Frame API: https://gist.github.com/SplendidAlakey/49e98bbb3a24394ad8346a5132cc21c3#file-frame_crash-log
https://gist.github.com/SplendidAlakey/49e98bbb3a24394ad8346a5132cc21c3#file-frame_latest-log

Logs for Kambrik: https://gist.github.com/SplendidAlakey/49e98bbb3a24394ad8346a5132cc21c3#file-kambrik_crash-log
https://gist.github.com/SplendidAlakey/49e98bbb3a24394ad8346a5132cc21c3#file-kambrik_latest-log

Logs for Pehkui: https://gist.github.com/SplendidAlakey/49e98bbb3a24394ad8346a5132cc21c3#file-pehkui_crash-log
https://gist.github.com/SplendidAlakey/49e98bbb3a24394ad8346a5132cc21c3#file-pehkui_latest-log

**Comment by AlexIIL** [comment]
> Beta 34 now takes 2.5min before the loading window opens, so the fix worked.

Yay! Hopefully there are other things we can look into optimizing, but at least that issue is fixed.

I've pushed beta 38, which fixes *some* of the crashes you've been having - can you retest?

**Comment by SplendidAlakey** [comment]
I jumped straight to beta 41, it took 3min to load, so I'll attach another snapshot, in case there's more that can be done, but overall 3min is a much less drastic increase from 2.5min, than 5min+ was: [snapshot_beta41_pre-loading-window.zip](https://github.com/QuiltMC/quilt-loader/files/10419878/snapshot_beta41_pre-loading-window.zip)

Also, the loading of the game now takes 5min45sec, as opposed to 4min30sec max on beta 28 and below, or 3min45sec on 0.17.x. Here's a snapshot I took, starting from a point where the loading window opens and ending once entering main menu: [snapshot_beta41_loading-window.zip](https://github.com/QuiltMC/quilt-loader/files/10419895/snapshot_beta41_loading-window.zip)

And all the aforementioned crashes have been resolved, but there are 2 more yet:

Frame API now crashes only if ReplayMod is present: https://gist.github.com/SplendidAlakey/49e98bbb3a24394ad8346a5132cc21c3#file-replaymod_crash-log
https://gist.github.com/SplendidAlakey/49e98bbb3a24394ad8346a5132cc21c3#file-replaymod_latest-log

Enchanted Shulkers: https://gist.github.com/SplendidAlakey/49e98bbb3a24394ad8346a5132cc21c3#file-shulkers_crash-log
https://gist.github.com/SplendidAlakey/49e98bbb3a24394ad8346a5132cc21c3#file-shulkers_latest-log

I think they are the same due to this line `Failed to select mixin config: #mm:mixins.mm.json`.

**Comment by AlexIIL** [comment]
It looks like 32 seconds of that is spent compressed files in-memory *before* copying them to the transform cache, which is unnecessary so beta 43 removes that. An additional 40 seconds is spent just copying files into the transform cache which isn't ideal but fortunately that only happens once per modset (in theory). I'll try optimizing that in the future though, since that seems a bit excessive :/

Erm, after the loading window opens the main slow path is checking if a file exists, taking 90 seconds total - however beta 43 might have indirectly made this faster by replacing most mod file systems with a zip file system, which might be faster. (If it's not there's more optimization that could be made by collaborating with QSL to speed this up).

Oh and beta 43 theoretically fixes the issue with MM/Fabric-ASM.

**Comment by SplendidAlakey** [comment]
The crash with MM is fixed, but Enchanted Shulkers still causes a (different) crash: https://gist.github.com/SplendidAlakey/49e98bbb3a24394ad8346a5132cc21c3#file-shulkers_crash-log
https://gist.github.com/SplendidAlakey/49e98bbb3a24394ad8346a5132cc21c3#file-shulkers_latest-log

Loading before the game window opens improved a bit, by around 15sec (from 3min down to 2min45sec): [snapshot_beta43_pre-loading-window.zip](https://github.com/QuiltMC/quilt-loader/files/10433446/snapshot_beta43_pre-loading-window.zip)

Loading of the game itself improved a lot, from 5min45sec down to 4min55sec, which is still a minute longer, than beta 28 and below, but not as bad: [snapshot_beta43_loading-window.zip](https://github.com/QuiltMC/quilt-loader/files/10433547/snapshot_beta43_loading-window.zip)

**Comment by AlexIIL** [comment]
Thanks for retesting! I've got an experimental fix for the enchanted shulkers crash - which is actually still a crash with MM (since the last crash was due to MM not being able to add new URLs to the class loader list, but the new crash was that quilt-loader refused to load classes from the added URL).

Beta 44 also adds a slight optimization to base mod loading, but that was only 16s of the loading time originally so I'm not expecting it to go down by much. I have some ideas on how to optimize populating the transform cache (which currently takes 35 seconds) but I haven't implemented them yet.

Oh, and your profiles are *really* helpful for this - but I think you could just take a single snapshot of the whole launch cycle? (From `Launch` in polymc to the main menu - taking shorter snapshots is useful if you don't want to wait around for the game to launch, but if you're getting everything you might as well only do it once).

**Comment by SplendidAlakey** [comment]
Unfortunately, I can't fully test it again, because a bunch of mods got broken. Affects beta 44, 45 and 46.

Enchanted Shulkers still refuses to work: https://gist.github.com/SplendidAlakey/49e98bbb3a24394ad8346a5132cc21c3#file-shulkers_crash-log 
https://gist.github.com/SplendidAlakey/49e98bbb3a24394ad8346a5132cc21c3#file-shulkers_latest-log

Incendium, ReplayMod, Structory, Structory Towers, Nullscape all cause a `java.io.UncheckedIOException: java.nio.file.NoSuchFileException` error with different codes. There might be more affected mods, because someone reported the same crash, but with yet another code https://forum.quiltmc.org/t/topic/626. It doesn't produce neither a crash nor a latest log, the error prints only to the launcher console: 
https://gist.github.com/SplendidAlakey/49e98bbb3a24394ad8346a5132cc21c3#file-incendium_launcher-log
https://gist.github.com/SplendidAlakey/49e98bbb3a24394ad8346a5132cc21c3#file-replaymod_launcher-log
https://gist.github.com/SplendidAlakey/49e98bbb3a24394ad8346a5132cc21c3#file-structory_launcher-log
https://gist.github.com/SplendidAlakey/49e98bbb3a24394ad8346a5132cc21c3#file-structorytowers_launcher-log
https://gist.github.com/SplendidAlakey/49e98bbb3a24394ad8346a5132cc21c3#file-nullscape_launcher-log

Without these mods it takes me 2.5min or so before the loading window opens and then 4min20sec to load into the game, which is almost on par with 0.17.10, but since it's not a full test without these mods, I can't say the issue is completely fixed yet.

And I've been making separate snapshots, because I figured it's easier to go through them, when they are separated. If that's not the case, I'll just be capturing the entire loading process instead. Let me know whichever is preferable for you.

**Comment by AlexIIL** [comment]
Thanks for retesting, I've fixed both bugs (assuming the last bug is the same bug that occurs with *any* mod that included empty folders inside their jars - I've only tested Enchanted Shulkers and Nullscape).

> And I've been making separate snapshots, because I figured it's easier to go through them, when they are separated. If that's not the case, I'll just be capturing the entire loading process instead. Let me know whichever is preferable for you.

Single snapshot please! A profiler snapshot lets me look at how long different parts of code take to run - and since "loading quilt loader" and "loading the game" are from different parts of the code it's quite easy to see which is which.

**Comment by SplendidAlakey** [comment]
Alright, every single crash has now been fixed. 

The loading times are now almost the same as beta 28 and below. Before the game window opens it's back to 2.5min, which is fully on par with beta 28. Game loading sometimes takes 4min25sec, sometimes 4min45sec, not sure why. Here's a snapshot of when it takes the longest: [snapshot_beta49.zip](https://github.com/QuiltMC/quilt-loader/files/10465566/snapshot_beta49.zip) (takes 1min25sec before the game window and 4min5sec to load the game on 0.17.10; vs 2min30sec before the game window and 4min45sec on 0.18.1-beta.49).

Thanks a lot for all the fixes.

**Comment by AlexIIL** [comment]
Okay, I've released beta 51 which has got basically all of the optimizations that I first thought of - it uses a much more optimized system for reading and writing the transform cache, which took ~55 seconds last time - hopefully that helps a bit.

*Edit: I've released beta 52, which has more optimizations. Hopefully that's the last one for tonight? :P*

The game sometimes taking 4min25sec and sometimes taking 4min45sec sounds a bit concerning - and I'm wondering if that's the transform cache incorrectly getting regenerated on some launches? I'd be interested in a log file from one of those launches - in particular if it contains any log lines like:
```
[04:48:40] [main/INFO] (Quilt Loader/Cache) Not reusing previous transform cache since it has different keys:
[04:48:40] [main/INFO] (Quilt Loader/Cache) Different: 'mod:minecraft_test': 'e7 07 01 15 01 29 1a 66 92 74 16 ' -> 'e7 07 01 15 04 30 27 a4 dd 94 39 '
[04:48:40] [main/INFO] (Quilt Loader/Cache) Different: 'mod:quilt_loader': 'e7 07 01 15 01 29 1a b2 68 75 16 ' -> 'e7 07 01 15 04 30 27 10 f0 96 39 '
```
(I'm especially interested in fixing bugs like this because we're going to use that transform cache for chasm transformations in the future, which will take longer to process but should only happen when you add or remove mods, or change relavent config options).

**Comment by SplendidAlakey** [comment]
Ok, so the loading before the game window opens improved even further, from 2min30sec down to 2min; game loading improved from 4min45sec to 4min30sec, when re-caching stuff and I can't test with it reusing previous one, due to the issue you mentioned.

Yes, there are indeed such lines, this is the log of the instance I ran to capture the last snapshot: https://gist.github.com/SplendidAlakey/1a419092e9887e1de9fbb7506b88dc47. There are also a bunch of `Multiple paths added for '/', but only a single one can be returned!` errors, that used to not be there. I specifically made sure not to change any mods between the tests and even ran it a few times in a row to notice the times. I've also ran the instance a couple more times just now and `mod:forge_tags`, `provided-mod:porting_lib_tags`, `provided-mod:forge_tags` and `porting_lib_tags` are the exact same entries, that force the re-caching.

**Comment by AlexIIL** [comment]
> from 2min30sec down to 2min; game loading improved from 4min45sec to 4min30sec,

Huh, that's actually a bit more that I thought it would be! Optimizing further from this point might require trying to optimize other mods, since I'm really running out of ideas for optimizing quilt-loader itself.

> There are also a bunch of Multiple paths added for '/', but only a single one can be returned! errors, that used to not be there.

I guess this would be a good reason for me to actually write changelogs with each release - that's a new warning in one of the betas. It's intended to be show where multiple mods have included the same resource but they are being accessed in a way which only allows one of them to be used - so this won't log a warning if multiple mods contain a common non-replacing tag json, for example. This specific case is quite weird though - apparently a mod is looking for the first "root" folder on the classpath, which is odd since every entry in the classpath contains a root folder! I'll change the warning for `/` to show the caller's stacktrace instead of every entry in the classpath.

>  `mod:forge_tags`, `provided-mod:porting_lib_tags`, `provided-mod:forge_tags` and `porting_lib_tags`

It looks like this is a solver bug - basically loader doesn't perform version comparison when selecting mods for `provides`, so the solver thinks there's no difference between the two options - even though the versions provided are hopefully different.

**Comment by SplendidAlakey** [comment]
Yeah, this issue can pretty much be closed, as the loading times are on par with beta 28. Not as fast as 0.17.10, but I assume that's not really possible, since 0.18.x adds a lot of new stuff. In any case, I consider current loading times acceptable.

> that's a new warning in one of the betas

So what do I do with the warnings? Report to the devs, Quilt or just ignore? As you can see, there are 119 of them and not just for the root folder.

> even though the versions provided are hopefully different

I can reproduce this by launching the same exact instance twice in a row, so these files aren't, or at least shouldn't be, different. Unless Create somehow changes it on every load?

**Comment by AlexIIL** [comment]
> So what do I do with the warnings? Report to the devs, Quilt or just ignore? As you can see, there are 119 of them and not just for the root folder.

Erm, I'll push a new beta which logs a more useful warning, and then I'd be interested in seeing a log from that.

The `/` root directory specifically is a different problem than the ones which include the same class file twice. I'll also push an update which includes the mods which contain those duplicate class files so it can be reported to them, eventually.

> I can reproduce this by launching the same exact instance twice in a row, so these files aren't, or at least shouldn't be, different. Unless Create somehow changes it on every load?

I'll open a new issue that describes this since i didn't do a very good job in my previous description :p

**Comment by AlexIIL** [comment]
> Erm, I'll push a new beta which logs a more useful warning, and then I'd be interested in seeing a log from that.

Okay, I've pushed beta 54 which adds this log.

**Comment by SplendidAlakey** [comment]
I'm afraid something went wrong again and the pre game loading takes 4min on beta 58: [snapshot_beta58.zip](https://github.com/QuiltMC/quilt-loader/files/10474161/snapshot_beta58.zip). Game loading itself seems unaffected, but I included the full snapshot anyway, just in case. I suspect `Not reusing previous transform cache since it has different keys` is the culprit, because it lists a lot of mods, that didn't change between sessions (I launched it twice in a row).

Also, Log Begone mod stopped working. When you compare my previous log to the new one, you can see almost double the amount of lines, specifically useless ones like `This line is printed by the mod mixin!`.

New logs: https://gist.github.com/SplendidAlakey/1a419092e9887e1de9fbb7506b88dc47

**Comment by AlexIIL** [comment]
It looks like 131 seconds is now spent reconfiguring loggers, which is very strange.

**Comment by AlexIIL** [comment]
Okay, beta 59 fixes a few classloading issues and *should* also fix Log4j not working correctly.

**Comment by SplendidAlakey** [comment]
Yep, every issue seems to be fixed. Pre game loading is back down to 2min, game loading itself is down to 4min15sec, logs are being correctly filtered. Thanks again! Feel free to @ me anytime you need more testing done.
