### ISSUE TITLE
Unable to run multiple instances in one directory

### ISSUE THREAD

**Issue by LostLuma** [QuiltMC/quilt-loader#200]
Hello, I've attempted to upgrade to the latest loader beta in my development setup and noticed that it's no longer possible to separately run a client and server, as loader crashes when it can not delete the other's transform cache. This is probably also an issue when using the vanilla launcher.

Crash log: https://files.lostluma.net/pbjmzZ.txt

I'm unsure which version this was exactly introduced in, as I've previously been using 0.17.6.

**Comment by AlexIIL** [comment]
That's an interesting usecase, but it makes sense. I suppose I can append the side to the transform cache (a bit like how the minecraft jar gets remapped to `.quilt/remappedJars/minecraft-1.19.3-0.18.1-beta.34/client-intermediary.jar`), I'm not sure about how to handle multiple clients running from the same directory though (although it might be okay since they should use the same cache... except in a development environment where the in-dev mods change every launch :/ )

**Comment by AlexIIL** [comment]
Okay I've [pushed](https://github.com/QuiltMC/quilt-loader/commit/21c012021e93ff40b9b3173e57d44c0e84d6f94a) beta 35 which uses a different file name for client vs server (by default) - hopefully that works?

**Comment by LostLuma** [comment]
That works fine yeah, thank you!
