### ISSUE TITLE
How ready is this project for people with no experiance making mods

### ISSUE THREAD

**Issue by tintin10q** [QuiltMC/quilt-loader#266]
Hi,

I am quite interested in making a minecraft mod. However, I have only attempted this once years ago (around 1.10.2 I think) using java and forge. However, I do feel I will have enough programing experience to be able to do it even though there will be a lot to learn. 

I looked around and I think I would like to use Quilt and write the mod in Kotlin. So my question is how ready is this project and QuiltMC as a whole to get started as someone that does not know how to minecraft mods but does have enough programming experience?  I ask this because when I looked at the wiki and docs or tutorials they were quite non existent and they assumed that you would know where to put code like (from the wiki website):

```kotlin
// ...
@Inject(method = ["createLivingAttributes"], at = [At(value = "RETURN")])
private fun addCustomAttribute(cir: CallbackInfoReturnable<DefaultAttributeContainer.Builder>) =
    cir.returnValue.add(GENERIC_JUMP_BOOST)
// ...
```

In addition the last commit on the [documentation repo](https://github.com/QuiltMC/developer-wiki/tree/main) was more than 4 months ago. This gives of the vibe that the project is not very alive. Al tough in contrast the mod-loader repo has a nice 1000+ commits with the last commit being a branch merge only 18 hours ago. This gives me the feeling this project is great for people who already know how to make mods but is not so beginner friendly. Please tell me if I am wrong. Also how up to date is the kotlin version?

Can anyone recommend a learning resource? Or is the best way to just download the template mod and trying to make things work?

**Comment by TheGlitch76** [comment]
Hi. Your best resource for learning about Quilt specifically would probably be asking questions on the [Discord server](https://discord.quiltmc.org), or alternatively the [forum](https://forum.quiltmc.org). 

Also, pretty much all of the principles in the [Fabric Wiki](https://fabricmc.net/wiki/) will apply to Quilt--a lot of the wiki covers vanilla content, and the Fabric-specific stuff can be used through Quilted Fabric API. You can start out by using only Fabric APIs, and switch to the QSL replacements (which are often very similar to the Fabric ones) once you're ready.

I'm going to close this issue because this isn't the right place to get help with these kinds of questions (seriously, very few people who are good at helping with modding questions watch this issue tracker.) Good luck!
