### ISSUE TITLE
Mod ID resolution for loader_dependencies overrides

### ISSUE THREAD

**Issue by sisby-folk** [QuiltMC/quilt-loader#317]
Hey gang, I've bumped up against the quilt_loader_dependencies.json implementation and while the ability to specify mod path increases the accuracy of how the dependency change is applied, it makes it straight useless for use cases that work great in fabric.

Here's an example - we maintain a modpack that contains [MemoryLeakFix](https://modrinth.com/mod/memoryleakfix) - every update, memory leak fix bumps the required floader version to the absolute latest. As expected, this breaks our quilt pack half the time because the embedded floader version in qloader is a little out of date.

Easy solution - target the mod with ID `memoryleakfix` and just totally remove the `fabricloader` dependency, then completely forget about the issue and freely update memoryleakfix whenever you want.

Problem - dependency overrides can only target by paths. Paths change every mod update. For modpack development that runs live and updates with the mods inside, this seems to fall a bit flat - I'm better off just disabling updates for the mod entirely. Seems like being able to use either a `path` key or an `id` key would resolve this.

**Comment by AlexIIL** [comment]
Technically just having `id` as a replacement to `path` wouldn't fix this since quilt requires the `remove` or `replace` types to be an exact match - which they won't if the required version of floader is increased everytime the mod updates.

I explicitly do *not* want to allow matching on just mod ids since that can fail to handle situations where a mod jar-in-jars multiple versions of a single sub-mod for compatibility, or if multiple different mods ship different versions of a library where you still only want the correct version to load. Basically, I've always viewed dependency overrides as a dangerous solution to bad dependencies, so I don't want to make it too easy to make changes that are too wide-reaching.

In this case however I'd much prefer adding support for overriding `provides`, so that you can override the version of fabric-loader that quilt-loader provides. Would that work for you? (I'll have to change how classpath paths are exposed here since otherwise it won't work very well when distributing modpacks).

**Comment by sisby-folk** [comment]
I think that arises the same issue - I'd either have to bump the provided version arbitrarily high (which could cause uncaught crashes from mods that actually need a new floader feature in future), or I'd have to bump the number every loader update.

Plus I don't actually have control over the loader version as a modpack author - we recommend prism and prism let's you swap it whenever you want. So it'd have to target all versions of the loader and that sounds... much messier.

**Comment by sisby-folk** [comment]
Speaking to the design though, using these dependency overrides is definitely like checking an "I know what I'm doing" tickbox, except the hazard here is I feel like I've checked it and then I find out the training wheels are still on and I can't take hard corners :P

**Comment by AlexIIL** [comment]
> every update, memory leak fix bumps the required floader version to the absolute latest

From looking around the source code of MemoryLeakFix a bit it seems like they only bumped the fabric-loader version requirement 3 times:

- `0.11.3` was the initial version.
- `0.11.3` -> `0.14.8` <https://github.com/fxmorin/MemoryLeakFix/commit/fd8dff6239453ba3f5a101925ab02960cdf5f678>
- `0.14.8` -> `0.14.11` with the move to architectury (across 3 commits)
- `0.14.11` -> `0.14.21` <https://github.com/fxmorin/MemoryLeakFix/commit/2d4aab99042c04c04e144e5c6fcf26aecac67386>

The most recent bump looks like it was necessary - something changed internally in what fabric loader does with mixins, which means MemoryLeakFix was able to remove a bunch of code which fixed a problem (although I haven't looked into exactly what the problem was).

> (which could cause uncaught crashes from mods that actually need a new floader feature in future)

Could the same thing happen here? A MemoryLeakFix  update might genuinely need an floader update at some point, and a blanket removal of the dependency will happily ignore that.

To be honest though, it sounds like you don't actually need to increase the dependent version arbitrarily high - just remove a very specific version, and update the override whenever a new version of MemoryLeakFix bumps the required version. As such I guess I can add `id` as a way to target a mod, which may only be present *once* in the mods folder.

*(Okay, so the *real* fix here is for me to update the provided version of floader as quickly as the QFAPI/QSL teams update to newer versions of minecraft - rather than lagging behind all the time).*

**Comment by AlexIIL** [comment]
Added in https://github.com/QuiltMC/quilt-loader/commit/8d7c9fd8ec1451b069237fe0dda7a88eb621a09d - not released quite yet.
