### ISSUE TITLE
Quilt crashes if XDG_CONFIG_HOME does not exist

### ISSUE THREAD

**Issue by JulianVennen** [QuiltMC/quilt-loader#327]
Quilt loader 0.19.2-beta.4 crashes if the XDG_CONFIG_HOME does not exist, as it throws an error in this case:
https://github.com/QuiltMC/quilt-loader/blob/develop/src/main/java/org/quiltmc/loader/impl/util/GlobalPaths.java#L62

This is probably not the right action here, especially if XDG_CONFIG_HOME isn't even set. I think the best option would be to attempt to create it.

I'm also a little confused why this throws an Error instead of an Exception. A missing config directory should is not a fatal, unrecoverable error.

**Comment by AlexIIL** [comment]
If `XDG_CONFIG_HOME` doesn't exist them it will return `null` here: https://github.com/QuiltMC/quilt-loader/blob/8d7c9fd8ec1451b069237fe0dda7a88eb621a09d/src/main/java/org/quiltmc/loader/impl/util/GlobalPaths.java#L52
and be handled by the lines here:
https://github.com/QuiltMC/quilt-loader/blob/8d7c9fd8ec1451b069237fe0dda7a88eb621a09d/src/main/java/org/quiltmc/loader/impl/util/GlobalPaths.java#L53-L59
It will crash if `XDG_CONFIG_HOME` is set to an empty value though, which is apparently allowed by the spec: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

> I'm also a little confused why this throws an Error instead of an Exception. A missing config directory should is not a fatal, unrecoverable error.

It''s a problem because mods are presumed to want to use that directory - and it *nearly* matches the behavior for local config paths, except it doesn't try to create it (which I'll change it to do so):
https://github.com/QuiltMC/quilt-loader/blob/8d7c9fd8ec1451b069237fe0dda7a88eb621a09d/src/main/java/org/quiltmc/loader/impl/QuiltLoaderImpl.java#L239-L254

**Comment by JulianVennen** [comment]
I meant that it crashes if the environment variable isn't set and the default path doesn't exist, thank you for working on this.

**Comment by AlexIIL** [comment]
Okay, thanks for spotting it!
