### ISSUE TITLE
Quilt Parsers should follow Quilt JSON5's publicness

### ISSUE THREAD

**Issue by EnnuiL** [QuiltMC/quilt-loader#331]
Currently, there is a botched attempt to relocate the Quilt Parsers library to an internal path while it's treated as some sort of internal library; However, Quilt JSON5 has been exposed as a public library that is included on `quilt-installer.json` and that mods could use;

Considering the massive usefulness of Quilt Parsers? I believe it should be exposed as a public library just like Quilt JSON5 is, and heck, we should also expose the GSON adapters due to their usefulness

**Comment by TheGlitch76** [comment]
You'll notice that quilt-json5 is deprecated starting in 0.20. We're intentionally not exposing parsers because we want the opportunity to swap them out (as we did for quilt-json5 -> quilt parsers, and we want to do for TOML if something better ever appears).
If Loader became tied to Minecraft versions, then I'd be happy to expose it, but otherwise (pending a veto by Alex) it's staying hidden.
Perhaps we could work something out to include a public version with QSL?

**Comment by EnnuiL** [comment]
I understand; Honestly, having it as a library mod does look like a good option! I was planning to have Quilt JSON5 published as a Fix Ennui Stuff library mod and yeah, by having it be a mod in the first place, it would prevent this situation from happening in the future;

We could somehow investigate exposing Quilt Parsers on QSL, but that will require extra thoughts :p
